services:
  minio:
    image: minio/minio:RELEASE.2022-06-11T19-55-32Z
    container_name: miqroforge-minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=miqroforge
      - MINIO_ROOT_PASSWORD=miqroforge@2025.
    volumes:
      - ./data/minio:/data
    command: server /data --address ":9000" --console-address ":9001" 
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 40s
    networks:
      - default

  mysql:
    image: mysql:8.0
    container_name: miqroforge-mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=miqroforge@2025.
      - MYSQL_DATABASE=miqroforge
      - MYSQL_USER=miqroforge
      - MYSQL_PASSWORD=miqroforge@2025.
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./config/miqroforge.sql:/docker-entrypoint-initdb.d/miqroforge.sql
    command: --default-authentication-plugin=mysql_native_password  
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      timeout: 20s
      interval: 10s
      retries: 10
      start_period: 40s
    networks:
      - default

  web:
    container_name: miqroforge-web
    depends_on:
      - minio
      - mysql
    image: miqroera01/miqroforge:v1.0
    restart: always
    ports:
      - "${SERVER_PORT:-30080}:80"
    environment:
      - "NFS_SERVER_IP=${NFS_SERVER_IP:?You must set the NFS_SERVER_IP environment variable}"
      - "NFS_SERVER_EXPORT_PATH=${NFS_SERVER_EXPORT_PATH:?You must set the NFS_SERVER_EXPORT_PATH environment variable}"
    volumes:
      - ./data/miqroforge/backend/logs:/opt/project/miqroforge/backend/logs
      - /etc/rancher/k3s/k3s.yaml:/opt/project/miqroforge/backend/misc/k8s/config
      - "${NFS_SERVER_EXPORT_PATH}:${NFS_SERVER_EXPORT_PATH}"
    networks:
      - default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 40s

networks:
  default:
    driver: bridge