version: '3.8'
services:
  minio:
    image: minio/minio:RELEASE.2022-06-11T19-55-32Z
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=miqroforge
      - MINIO_ROOT_PASSWORD=miqroforge@2025.
    volumes:
      - ./data/minio:/data
    command: server /data --console-address ":9001" --address ":9000"
    networks:
      - miqroforge-network

  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=miqroforge@2025.
    volumes:
      - ./data/mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password  
    networks:
      - miqroforge-network

  miqroforge:
    image: miqroera01/miqroforge:v1.0
    ports:
      - 30080:30080
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_DB=miqroforge
      - MYSQL_USER=miqroforge

networks:
  miqroforge-network:
    driver: bridge

  