spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:10.36.160.25}:/${MYSQL_DB:miqroforge_dev}?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: ${MYSQL_USER:miqroforge}
    password: ${MYSQL_PASSWORD:miqroforge@2025.}
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      # 初始连接数 计算节点
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置连接超时时间
      connectTimeout: 30000
      # 配置网络超时时间
      socketTimeout: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  
  jackson:
    serialization:
      write-empty-json-arrays: true
      write-dates-as-timestamps: true
  
# minio配置
minio:
  # 9000:32648, 9001:32464
  url: ${MINIO_URL:http://10.36.160.25:32004}
  accessKey: ${MINIO_ACCESS_KEY:admin}
  secretKey: ${MINIO_SECRET_KEY:Admin@123.}
  bucketName: ${MINIO_BUCKET_NAME:miqroforge}

# 项目数据配置
project:
  config:
    # logo地址
    logoUrl: "https://i.postimg.cc/kGgPtJQV/miqro-era.png"
    # 短信验证码过期时间，单位秒
    email-code-expire-time: 90
    # 邮箱业务每日发送限制次数
    email-send-limit-count: 10
    # 项目名称
    name: miqroforge
    # 默认卷信息
    default-volume: nfs
    # 计算容器内默认挂载路径
    default-volume-mount-path: /data/miqroforge
    # 解析文件名后缀
    resolve-file-suffix:
      - json
    # 任务运行模式 QUEUE : 队列模式 SINGLE : 单任务模式
    run-mode: QUEUE
    job:
      # 默认作业重试最大次数
      max-retry-count: 3
      # 任务失败重试次数
      backoff-limit: 1
      # 作业保留时间: unit： second
      ttl-seconds-after-finished: 7200
      # 默认CPU资源 核
      default-cpu: ${DEFAULT_CPU:4}
      # 默认内存资源 Gi
      default-memory: ${DEFAULT_MEMORY:1}
      # default params filename
      default-params-filename: params.json
      # 默认参数文件 key
      default-params-key: config_path
    # agent 配置
#    agent:
#      # agent 地址
#      scheduling:
#        url: http://10.36.160.25:8000/agentic-scheduler/exec

logging:
  level:
    com.era.miqroforge: info

# 存储配置
storage:
  nfs:
    server: ${NFS_URL:10.36.160.25}
    path: /data/nfs/miqroforge
    mount: /data/miqroforge
    task-work-dir: task
    node-work-dir-prefix: node
    job-work-dir-prefix: job

kubernetes:
  config-path: misc/k8s/config